version: "3"
services:
  # web:
  #   image: node:10.16.0
  #   user: node
  #   working_dir: /app
  #   environment:
  #     - PORT=3000
  #   volumes:
  #     - ./build:/app # 将本地目录映射到容器内
  #   ports:
  #     - 3000:3000 # 本地端口:容器端口
  nginx:
    image: nginx:1.15
    restart: always
    working_dir: /home/static
    volumes:
       - ./build/:/usr/share/nginx/html
      #  - ./nginx.conf:/etc/nginx/nginx.conf # 映射 ginx 配置文件
    ports:
      - 3000:80 # 绑定容器的80端口到本的1080端口
